services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - app-network
    ports:
      - "5434:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    networks:
      - app-network
    ports:
      - "8081:8080"

networks:
  app-network:
    driver: bridge

volumes:
  pgdata : {}